name: Publish Packages

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./src
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
       PROJECT_FILE_PATH: src/Cron.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}
       VERSION_REGEX: (?(?<=[a-z])[1]|((?:\.?[0-9]+)(?:\.?[0-9]){3,}(?:[a-z]+)?))
       
